apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc-fast-food
  name: api-loadbalancer-svc-fast-food
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: api-fast-food-deployment
  type: LoadBalancer