apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-loadbalancer-svc
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-pod
  type: LoadBalancer