apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-pod
spec:
  containers:
    - name: postgres
      image: postgres:15.1-alpine
      ports:
        - containerPort: 5432
