apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_URL: "jdbc:postgresql://a0fe55cb1a86544ca854b183484e96bd-1243182406.us-east-1.elb.amazonaws.com:5432/postgres"
  POSTGRES_USER: "admin_db"